export const brandsData = [
  { name: "Logitech", category: "Keyboards, Mice, Webcams & Headsets", tag: "Peripherals & Video" },
  { name: "HP", category: "Commercial Laptops, Desktops, Power Adapters & Printers", tag: "Computing & Printing" },
  { name: "Dell", category: "Enterprise Workstations, Laptops & Accessories", tag: "Enterprise Computing" },
  { name: "Lenovo", category: "ThinkPad Laptops, Desktops & Power Adapters", tag: "Corporate Computing" },
  { name: "TP-Link", category: "Switches, Routers, Access Points, Wi-Fi Adapters & PoE", tag: "Networking Infrastructure" },
  { name: "Ugreen", category: "USB-C Hubs, Docking Stations, Display Cables & Adapters", tag: "Connectivity" },
  { name: "D-Link", category: "CAT6 Cables, Patch Panels, Patch Cords & Fibre Patch", tag: "Structured Cabling" },
  { name: "SanDisk", category: "Flash Drives, Type-C OTG Drives, SD & MicroSD Cards", tag: "Flash Storage" },
  { name: "Seagate", category: "External Hard Disk Drives & Desktop Storage", tag: "Data Storage" },
  { name: "Samsung", category: "Portable External SSDs, Internal NVMe & Monitors", tag: "High-Speed SSDs" },
  { name: "Crucial", category: "DDR4 & DDR5 RAM Memory, SATA & NVMe SSDs", tag: "Memory & Storage" },
  { name: "WD", category: "NVMe SSDs & WD Purple Surveillance Hard Drives", tag: "Storage & Surveillance" },
  { name: "APC", category: "Smart-UPS, Back-UPS Systems & Power Protection", tag: "UPS & Power" },
  { name: "Belkin", category: "Surge Protectors & High-Speed Charging Accessories", tag: "Power Protection" },
  { name: "Epson", category: "EcoTank Printers, Thermal POS Receipt Printers & Dot Matrix", tag: "Business Printing" },
  { name: "Brother", category: "High-Speed Thermal Label Printers & Multifunction Units", tag: "Labeling & Printing" },
  { name: "Canon", category: "High-Speed Document Scanners & Office Printers", tag: "Document Digitization" },
  { name: "Honeywell", category: "Laser Barcode Scanners, CCTV Power Supplies & Racks", tag: "Scanning & CCTV Power" },
  { name: "Hikvision", category: "IP Cameras, Dome, Bullet, PTZ, DVRs & NVR Systems", tag: "CCTV & Security" },
  { name: "Jabra", category: "Executive Conference Speakerphones & Business Headsets", tag: "Conferencing Audio" },
  { name: "JBL", category: "Commercial Bluetooth Headsets & Portable Speakers", tag: "Professional Audio" },
  { name: "Creative", category: "Desktop Soundbars & Audio Systems", tag: "Audio Solutions" },
  { name: "Fellowes", category: "Cross-Cut Security Paper Shredders", tag: "Office Shredding" },
  { name: "GBC", category: "A3 & A4 Thermal Laminating Machines", tag: "Office Equipment" },
  { name: "Finolex", category: "Shielded Coaxial CCTV Cables & Network Wires", tag: "Cabling & Security" },
  { name: "Cooler Master", category: "80 PLUS SMPS Power Supplies & Cooling Accessories", tag: "Hardware Components" },
  { name: "Corsair", category: "High-Efficiency Computer Power Supplies & Memory", tag: "Hardware Components" },
  { name: "Arctic", category: "High-Performance CPU Thermal Paste Compounds", tag: "IT Servicing" },
  { name: "Noctua", category: "Industrial Grade Cooling Fans & Thermal Paste", tag: "Hardware Servicing" },
  { name: "iFixit", category: "Precision Electronics Toolkit & Hardware Repair", tag: "Maintenance Tools" },
  { name: "ORICO", category: "SATA Hard Drive Enclosures & USB 3.0 Adapters", tag: "Enclosures & Tools" },
  { name: "TVS", category: "Thermal Transfer Barcode & Ticket Printers", tag: "POS Equipment" },
  { name: "GM", category: "Heavy Duty Master Switch Extension Power Strips", tag: "Power Accessories" },
  { name: "Portronics", category: "Electric High Power Air Dusters & Laptop Accessories", tag: "IT Accessories" },
  { name: "Zebronics", category: "Budget Mechanical Keyboards & Computer Peripherals", tag: "Input Peripherals" },
  { name: "Redragon", category: "Mechanical Keyboards & Heavy Duty Typing Input", tag: "Mechanical Keyboards" }
];
